### PR TITLE
WAZO-680 provd API version in URL

### PR DESCRIPTION
**Pull request by bloom1**

### CODE REVIEW

**Comment by sduthil** [comment]
I see xivo-provd-client (the older repo) is not modified. Is it completely deprecated? Or should it be modified too, for retrocompatibility?

**Comment by bloom1** [comment]
The old client does not work since I added authentication to provd. Also, the repo is archived :)

**Comment by sduthil** [comment]
I see another reference to `/provd` in [`wazo_provd_client/operation.py`](https://github.com/wazo-pbx/wazo-provd-client/blob/wazo-19.07/wazo_provd_client/operation.py#L79). Did you leave it on purpose?

**Comment by bloom1** [comment]
> I see another reference to `/provd` in [`wazo_provd_client/operation.py`](https://github.com/wazo-pbx/wazo-provd-client/blob/wazo-19.07/wazo_provd_client/operation.py#L79). Did you leave it on purpose?

Nope. :) I will change it thanks!

**Pull request closed without merging**
